apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vending-machines-dev-argocd
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: vending-machines-dev
    server: "https://kubernetes.default.svc"
  source:
    path: dev
    repoURL: "https://github.com/edraven-dev/ddd-vending-machines-k8s"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vending-machines-prod-argocd
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: vending-machines
    server: "https://kubernetes.default.svc"
  source:
    path: prod
    repoURL: "https://github.com/edraven-dev/ddd-vending-machines-k8s"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
