apiVersion: v1
kind: ConfigMap
metadata:
  name: vending-machines-atm-config
  namespace: vending-machines-dev
data:
  DB_HOST: postgres.postgres.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: vending-machines-dev-atm
  GRPC_URL: "0.0.0.0:9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm-deployment
  namespace: vending-machines-dev
  labels:
    app: atm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm
  template:
    metadata:
      labels:
        app: atm
    spec:
      containers:
      - name: atm
        image: ghcr.io/arkadiuszkolodynski/ddd-vending-machines/atm:c3c279e4c0da81077b35afa88f8eb9066af58402
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: vm-secrets
              key: RABBITMQ_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: vending-machines-atm-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: vending-machines-atm-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: vending-machines-atm-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vm-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: vending-machines-atm-config
              key: DB_NAME
        - name: GRPC_URL
          valueFrom:
            configMapKeyRef:
              name: vending-machines-atm-config
              key: GRPC_URL
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: atm-service
  namespace: vending-machines-dev
spec:
  selector:
    app: atm
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atm-ingress
  namespace: vending-machines-dev
spec:
  rules:
    - host: "dev-vending-machines.edraven.dev"
      http:
        paths:
          - pathType: Prefix
            path: /api/atm
            backend:
              service:
                name: atm-service
                port:
                  number: 3000